# Train + Eval Faster R-CNN — Car Damage Detection

Notebook này train **Faster R-CNN** bằng PyTorch/Torchvision với cấu hình giống YOLOv8s:

- `epochs = 30`
- `batch = 16`
- `imgsz = 640`
- eval trên cùng tập `val` trong `data.yaml`
- tính COCO metrics bằng `torchmetrics`: `mAP@50:95`, `mAP@50`, `mAP@75`, `mAR`

> Lưu ý: trong thực tế người ta thường dùng **Faster R-CNN** thay vì Fast R-CNN gốc, vì Faster R-CNN có RPN tạo proposal end-to-end. Notebook này dùng `fasterrcnn_resnet50_fpn`.

> `batch = 16` với Faster R-CNN có thể rất tốn VRAM. Notebook giữ đúng cấu hình bạn yêu cầu; nếu bị CUDA OOM thì giảm `BATCH` xuống `2`, `4` hoặc `8`.

In [1]:
# Nếu chạy trên Google Colab, mount Google Drive để lưu kết quả
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!unzip "/content/drive/MyDrive/coco_damage_car_yolov8.zip" -d "/content/data"

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: /content/data/coco_damage_car_yolov8/train/images/003120_jpg.rf.Dqo3IY3vqjeG5Laq1jRZ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003121_jpg.rf.gook4XJCLIJhUAFFgUnM.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003122_jpg.rf.Clplyzl40NlRPlPInKwV.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003123_jpg.rf.R3CR81AtaL9UcP3BgGbt.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003124_jpg.rf.WSZfqewyivwLqAZ9NVCd.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003125_jpg.rf.xGGGhMrDFmWZe1E60hbX.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003126_jpg.rf.MZWDtqSxCVhhr19QSBfG.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003127_jpg.rf.fNH8ysJrDGAEbkqkHeo0.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003128_jpg.rf.niGlfkFZxXbEeieWz932.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003129_jpg.rf.NqoGXn9CA6rEGyh212l5.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003130_jpg.rf.gDJ0kJqCCGOHrelNbHRW.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003131_jpg.rf.qoPX9dd8P7CGMm0kAUEC.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003134_jpg.rf.jKxwj1cLF6ziQeer758W.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003136_jpg.rf.5KZevJPlnKYswMuUPy8y.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003137_jpg.rf.opMkNNW2025VeTuPLMnd.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003141_jpg.rf.ANonPk4AbG7w1gVY6dLH.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003142_jpg.rf.rbOxYuNbByXpTUhlsKvl.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003145_jpg.rf.zqg5PJAkqisIyjGehqlh.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003147_jpg.rf.ViL89gRwa1PQoKDqll7T.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003148_jpg.rf.16ZYMStMZrTU8TspgVAZ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003149_jpg.rf.TX4Bjq77zIUnqMfGh8yr.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003151_jpg.rf.raH1oiFFolFRvBmcxZLu.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003152_jpg.rf.HrAuugmuV5H6AAJ5Y7pA.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003153_jpg.rf.PDf68vZ5IRFQGQhb6W6z.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003154_jpg.rf.3TL2dhZqPXGuRFXlGGVa.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003155_jpg.rf.6Yjv38rTep4UMYqLZg43.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003157_jpg.rf.4gfRvWOXXsV9wNajPUJc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003158_jpg.rf.u6DKw4zQGNWhcz1siLXQ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003159_jpg.rf.FitI4B1KaCQbAh0TyrqV.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003160_jpg.rf.tHcBMFFkUebro0qjyCbJ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003163_jpg.rf.lbTCduUSx5XgNv7VS6B9.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003164_jpg.rf.im2XyvCPNNtGqEX7Oofc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003165_jpg.rf.maMKzVlk14zXGoc37cuA.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003166_jpg.rf.f3oQ9YGTtmNuI1yU3zXD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003167_jpg.rf.vgVm6Zib59kS5wOAhPom.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003168_jpg.rf.CKW01FTWo777RlQOEDEp.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003170_jpg.rf.5YLcR3njzwuySk3ACTpP.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003171_jpg.rf.uPNv4wDJLsoHVkMHLZ1d.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003172_jpg.rf.kzqkTp30ncccxaoh3xVo.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003173_jpg.rf.eLO0H7Z03JMATPuZFVkJ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003175_jpg.rf.lzJZq73eL7ewDRzCVF1n.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003177_jpg.rf.kcA6R1cCjvHHVGerFp09.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003178_jpg.rf.qHuqFpktd5IgP19JTbHm.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003179_jpg.rf.ZOaXIsGJ1TO1LAQYxfZR.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003182_jpg.rf.tdIwquDfFL7UEaWtjARn.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003183_jpg.rf.xjVUdEqGQwLbnWOXRF9Z.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003184_jpg.rf.IrqSUEeh8stRycA2gH8X.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003186_jpg.rf.zWXJ0UfGI5SYzA6dlps2.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003187_jpg.rf.NAoiv9Xsj4TigkMEspx8.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003188_jpg.rf.KjARirOKXvdxG7eTLq02.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003189_jpg.rf.0tXObiot9fefZ5YN7hPw.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003190_jpg.rf.XpJSouuqJdNiPjcKukOe.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003191_jpg.rf.Epay9hrtWHpUAIzfsTaI.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003192_jpg.rf.ZfqWmH4uU4R0agpMj12a.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003193_jpg.rf.2zmoPyBmduOxxwUQnS6s.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003195_jpg.rf.k0Fd0wQ7en3ZeLkqj0Hc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003196_jpg.rf.NF9RLRgSPKgVVIkOwZrR.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003197_jpg.rf.QDHEN9AsgZgFRkho0Ml4.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003198_jpg.rf.QeeGGK7NsYlZsnWGHu4o.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003199_jpg.rf.Hp2szImLCNfTajCqq2qN.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003201_jpg.rf.7x1xS1GrCEyAc5UmkW5a.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003202_jpg.rf.BxLbuJzYroM46oDHZesl.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003205_jpg.rf.5XfiLHDSO0lb37S2n4wl.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003206_jpg.rf.fMFGO6r71DAgUKJilIdM.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003207_jpg.rf.ng9aFHOUOZyh6qHeO5mv.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003208_jpg.rf.LqFiLX1qWg3OQGGvd9tC.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003209_jpg.rf.yE0iA01RWqu8cJSCPqyT.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003210_jpg.rf.RuQ4sI630TJ1bOecCKkc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003211_jpg.rf.NOZOTwcGSvCc1tSHn3IE.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003212_jpg.rf.NsITPiZNZrLGhRrN4DKU.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003214_jpg.rf.PMqkIisu39IclOAGDYhF.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003216_jpg.rf.TQzBwzqM54HwnOPtSxkk.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003218_jpg.rf.DwYJEcTGW4VVOWW7Ko1n.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003219_jpg.rf.G3ttZl7OWSRdYNhMm2vt.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003220_jpg.rf.JLYZjxBE8gXEQAGISscI.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003222_jpg.rf.HPfsXNMsZvOtuKn73kfb.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003226_jpg.rf.tvyKmswevYKlFtJ9iOiD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003227_jpg.rf.1G6uJkGgG9WxMf8cBdZM.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003229_jpg.rf.QVJUKlN8HEcqG5vRfMX8.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003230_jpg.rf.4YuRZHKZAcVzhiBFJgWI.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003233_jpg.rf.7NjjKAuYC4Ypusi9klPw.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003234_jpg.rf.44EjbXRSjldROmyi7YRP.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003236_jpg.rf.gc9luM0Mxj4YylWXmXo9.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003237_jpg.rf.f0KZWEbJaXHwW4SzAZ7U.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003238_jpg.rf.bltuYXKJHHSduRwQNLls.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003239_jpg.rf.lFF6GzTonSO8XbpSYsp9.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003240_jpg.rf.49xXffti7xQXrLpRutMU.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003241_jpg.rf.OMTsVKIpwAxVzBa7lhrm.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003242_jpg.rf.GZhSB8Sk7vmuNn9LLDdW.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003243_jpg.rf.RcbgSO9XxT4m4TTepTWb.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003245_jpg.rf.4WteC1IP9NqO1RoWtUP4.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003248_jpg.rf.WwijwnRP5rm9rfdnODOD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003250_jpg.rf.j23iT240ALUVCumXAhgw.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003251_jpg.rf.m4qes55zb9QrJxaM2hMI.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003252_jpg.rf.Km7hJLCkk8gihmPFxD7E.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003254_jpg.rf.1nYjKGqChLNQCWBsc9vn.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003255_jpg.rf.okZDNLiTxuuHM6hIcexc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003256_jpg.rf.XJ6nb71F69ejYR0jQDOc.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003258_jpg.rf.FN31nr255H2dYX5b8UYw.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003259_jpg.rf.7ENFVFbSfJc98Xvneazd.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003260_jpg.rf.m2GTHWyMEBXXWZpdX5Cq.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003261_jpg.rf.AUIJmlEfEQhXwicyNG6k.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003262_jpg.rf.lj6ji2huVZ6OwT5zJ0W0.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003264_jpg.rf.YgahOvUuAIjtHCiNHQo5.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003267_jpg.rf.dYcQgQmRQXeGs9Yz7zVh.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003269_jpg.rf.u9zm4nWNrRO31JNjs8Zd.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003270_jpg.rf.gwiOrmfHCIaDo9iGRA1H.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003275_jpg.rf.aWr9grmxwZQDAE8pYeyC.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003276_jpg.rf.ejZyyIva9eoyQZclDZ5y.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003277_jpg.rf.xE2pb7YNRnNaB9ZRZrlD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003278_jpg.rf.BkJrO79dg7LHjR5e14uy.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003279_jpg.rf.cck7Ts7PemCeCw2rop3n.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003280_jpg.rf.hZpBPYSzwswH7LsgfzmR.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003282_jpg.rf.j9nJ7oSl7pNTrYqNrBTl.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003286_jpg.rf.9K6AaiK1joSkaYIb3I5V.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003288_jpg.rf.Uvuh1T0hH3CJxTXEDfNT.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003289_jpg.rf.Ua4Qlu80RQ230lgGX8IZ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003292_jpg.rf.ArVI0YR31NwfiN9Iofoz.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003293_jpg.rf.ToBpURHfOuzSbzGCvIJL.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003294_jpg.rf.KQicKU8cJWqVSl0DplBA.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003295_jpg.rf.BO2rbpBEPNWsVtf7gFdX.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003297_jpg.rf.HQnyB3eLkvsz9EhlGY32.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003298_jpg.rf.Ngsvwl7MI3h4DcyId5Tb.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003299_jpg.rf.b4PWL6bUio9nKjLwpJKM.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003300_jpg.rf.ljS9C596hlLVxFGxZOOz.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003301_jpg.rf.CDRyu0gSQUXiBGJDKCn6.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003302_jpg.rf.FH0HK7PCrMfQoXG5F9cD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003304_jpg.rf.Hdzf8gcNe7Mg5BPh0Cpu.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003305_jpg.rf.UGRPg0Y0B1jkFHyKP0jP.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003306_jpg.rf.xBUmtxrGrrALgLkQEiLo.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003307_jpg.rf.6whk7D6XG6RFdLCPLld3.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003308_jpg.rf.G3mQsEtRRx6JLXotcGvL.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003309_jpg.rf.rR7UWWkLXOqdvMzhxCX9.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003310_jpg.rf.89WmiOX2oIoI1duhwFIN.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003312_jpg.rf.Y9eVweUwonZ33HKNOiqh.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003315_jpg.rf.uJTtt6DmfMIx8BqQ6gt0.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003316_jpg.rf.8BwXeSsbOi5WGkKHJOSU.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003318_jpg.rf.ELNpAVBcSPpoYYxZKeK1.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003319_jpg.rf.VQnR8NpQ9ytSxB8KJkn5.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003320_jpg.rf.NnB7KDQvmOWR1Yz4yB5M.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003321_jpg.rf.bdpOifv1PlCQvscnF4rP.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003323_jpg.rf.4s3KRTdq0eHcQlsRX49t.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003325_jpg.rf.VIc3EYo8S0XP2wXK5iSW.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003326_jpg.rf.N3CD6jn2OCG1WRudSlrE.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003327_jpg.rf.oMdTWh21pPEVolSaDqcn.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003328_jpg.rf.HwtaK1tAaSUDanq1lcXW.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003330_jpg.rf.ONXyxZzFyBrWZjPXsOJ7.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003335_jpg.rf.lRh31yeMYI8YnnBXgoCG.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003336_jpg.rf.l3rVrR3URjdDUgdnrJlA.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003339_jpg.rf.lZx5sTNq0LHPprwnIitd.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003340_jpg.rf.34wrak1cpvDSHMfYNQwg.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003341_jpg.rf.iuqIk9cWvTRy2TwAQvlD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003342_jpg.rf.ShXmDECQ0DwbEwYNJzK0.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003343_jpg.rf.S5KHqy8HMhO7yT55CXeI.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003345_jpg.rf.ZWhOx28gWmlXaHrzWJGD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003346_jpg.rf.Q0arCKwo6ccZnUvkcRXN.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003347_jpg.rf.bCzYavqo2Lsjze3QNcFy.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003349_jpg.rf.L1lc7ZtHjYBmYgSZEaFO.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003350_jpg.rf.LhJVrz1nyRb56QbAAPPf.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003352_jpg.rf.r2th0zgebiUxXOcSUYTz.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003355_jpg.rf.qKABohHwXyMLJ59zRWVo.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003356_jpg.rf.912SleAz9l86cx4LcuLY.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003358_jpg.rf.kUvNtHTWU35ZQ3eexWnm.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003359_jpg.rf.nV5iM583YtzMqaU0XPmF.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003361_jpg.rf.uudeGoyxc106yTPplz1z.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003364_jpg.rf.g2ULORaw33S4N7zYWOJ8.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003366_jpg.rf.rOB7OdIuyEQ5RbN42itR.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003367_jpg.rf.rOIqKwZxGEiJwZ8fckuP.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003369_jpg.rf.EIX1QXKjNRe6EITM4O0Q.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003371_jpg.rf.gGZM2XipPDRHezi14A9y.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003374_jpg.rf.zEsIz3frTszgYMvxW6lD.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003376_jpg.rf.zU6RXf5EGNVwWC2HfkKh.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003379_jpg.rf.NxK8V1MzS0Zqv7XTmsSl.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003380_jpg.rf.5Igf1tAxtdqCuBFJHKF3.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003382_jpg.rf.3BtG7zasMslWW7RYnH8C.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003383_jpg.rf.XOFOGQKcPOLUYR6Qxh5l.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003386_jpg.rf.maKQS7mwO3WZS22PvzZZ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003388_jpg.rf.1AabTCi4YC72hGerZ6Jg.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003389_jpg.rf.jYG4tZlgWFgfbKyxrG7Z.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003390_jpg.rf.R9xYXGocGbomGZEjVbvQ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003392_jpg.rf.fWKV3w2OmNxl4WwfJwtp.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003393_jpg.rf.Gx8JpclIrw76oWSpfmdj.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003394_jpg.rf.0fYLcFP2Xogf9v68RMEY.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003396_jpg.rf.BUrca9uILL3odroxkfMZ.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003398_jpg.rf.p2YDfQISmiDYxM6CW0Fi.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003400_jpg.rf.qIKTa9tkneoL01AcuYng.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003401_jpg.rf.kswOSfk1hn82EFyzYK1I.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003404_jpg.rf.2qA6z9bav4VHSu7YAVDb.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003405_jpg.rf.UA1Ads15GIslJjp5KGYm.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003406_jpg.rf.hZEZiinmLaQUZ8CBAgY3.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003407_jpg.rf.CfQde9KBup8UsRv9fSCf.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003408_jpg.rf.hSSbyafAZmqZRy8CSnzo.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003409_jpg.rf.xyLEEhL3aTUWHBAymA3s.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003410_jpg.rf.aSXJr5PoOcRAsr4PEuFw.jpg
  inflating: /content/data/coco_damage_car_yolov8/train/images/003411_jpg.rf.TmYemkoRw9xrQC0Yl0M7.jpg

In [3]:
!pip install -q torchmetrics pycocotools pyyaml pandas tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 25.9 MB/s eta 0:00:00

In [4]:
import os
import json
import yaml
from pathlib import Path

import torch
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import functional as F

from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection import FasterRCNN_ResNet50_FPN_Weights
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

from torchmetrics.detection.mean_ap import MeanAveragePrecision

## 1. Cấu hình train/eval

In [5]:
DATA_YAML = Path("/content/data/coco_damage_car_yolov8/data.yaml")

EPOCHS = 30
BATCH = 16
IMGSZ = 640

PROJECT_DIR = Path("/content/drive/MyDrive/coco_damage_car_yolov8")
RUN_NAME = "fasterrcnn_car_30e_640"
SAVE_DIR = PROJECT_DIR / RUN_NAME
SAVE_DIR.mkdir(parents=True, exist_ok=True)

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
USE_AMP = torch.cuda.is_available()

print("Device:", DEVICE)
print("Use AMP:", USE_AMP)
print("Data YAML:", DATA_YAML)
print("Save dir:", SAVE_DIR)

Device: cuda:0
Use AMP: True
Data YAML: /content/data/coco_damage_car_yolov8/data.yaml
Save dir: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640

## 2. Đọc `data.yaml` và chuẩn bị class names

YOLO dùng class id bắt đầu từ `0`, còn Faster R-CNN của Torchvision dành label `0` cho background. Vì vậy label thật sẽ được cộng thêm `1`.

In [6]:
with open(DATA_YAML, "r") as f:
    cfg = yaml.safe_load(f)

yaml_dir = DATA_YAML.parent

# Ưu tiên cfg['path'] nếu data.yaml có khai báo root dataset
if "path" in cfg and cfg["path"] is not None:
    dataset_root = Path(cfg["path"])
    if not dataset_root.is_absolute():
        dataset_root = (yaml_dir / dataset_root).resolve()
else:
    dataset_root = yaml_dir.resolve()


def resolve_split_path(p):
    p = Path(p)
    if p.is_absolute():
        return p
    candidate = dataset_root / p
    if candidate.exists():
        return candidate
    return yaml_dir / p

train_source = resolve_split_path(cfg["train"])
val_source = resolve_split_path(cfg["val"])

names = cfg["names"]
if isinstance(names, dict):
    class_names = [names[k] for k in sorted(names.keys(), key=lambda x: int(x))]
else:
    class_names = list(names)

num_classes = len(class_names) + 1  # +1 background

print("Dataset root:", dataset_root)
print("Train source:", train_source)
print("Val source:", val_source)
print("Classes:", class_names)
print("num_classes including background:", num_classes)

Dataset root: /content/data/coco_damage_car_yolov8
Train source: /content/data/coco_damage_car_yolov8/train/images
Val source: /content/data/coco_damage_car_yolov8/val/images
Classes: ['crack', 'dent', 'glass shatter', 'lamp broken', 'scratch', 'tire flat']
num_classes including background: 7

## 3. Dataset đọc YOLO format và convert bbox sang XYXY

YOLO label format:

```text
class_id x_center y_center width height
```

Torchvision detection target format:

```python
{
    "boxes": Tensor[N, 4],   # [x1, y1, x2, y2]
    "labels": Tensor[N],     # 1..num_classes-1, label 0 là background
}
```

In [7]:
IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def resolve_image_line(line, txt_file):
    p = Path(line.strip())
    if p.is_absolute():
        return p

    candidates = [
        txt_file.parent / p,
        dataset_root / p,
        yaml_dir / p,
    ]
    for c in candidates:
        if c.exists():
            return c
    return candidates[0]


def read_image_paths(source):
    source = Path(source)

    if source.is_file() and source.suffix.lower() == ".txt":
        paths = []
        with open(source, "r") as f:
            for line in f:
                line = line.strip()
                if line:
                    paths.append(resolve_image_line(line, source))
        return sorted(paths)

    if source.is_dir():
        paths = []
        for ext in IMG_EXTS:
            paths.extend(source.rglob(f"*{ext}"))
            paths.extend(source.rglob(f"*{ext.upper()}"))
        return sorted(set(paths))

    raise FileNotFoundError(f"Không tìm thấy image source: {source}")


def yolo_label_path_from_image_path(img_path):
    img_path = Path(img_path)
    s = img_path.with_suffix(".txt").as_posix()

    if "/images/" in s:
        return Path(s.replace("/images/", "/labels/"))

    # Fallback: .../train/img.jpg -> .../labels/train/img.txt
    return img_path.parent.parent / "labels" / img_path.parent.name / f"{img_path.stem}.txt"


class YoloFormatDetectionDataset(Dataset):
    def __init__(self, image_source):
        self.image_paths = read_image_paths(image_source)
        if len(self.image_paths) == 0:
            raise RuntimeError(f"Không tìm thấy ảnh trong: {image_source}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        label_path = yolo_label_path_from_image_path(img_path)

        img = Image.open(img_path).convert("RGB")
        w, h = img.size

        boxes = []
        labels = []

        if label_path.exists():
            with open(label_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue

                    parts = line.split()
                    if len(parts) < 5:
                        continue

                    cls, xc, yc, bw, bh = map(float, parts[:5])

                    x1 = (xc - bw / 2) * w
                    y1 = (yc - bh / 2) * h
                    x2 = (xc + bw / 2) * w
                    y2 = (yc + bh / 2) * h

                    x1 = max(0, min(x1, w - 1))
                    y1 = max(0, min(y1, h - 1))
                    x2 = max(0, min(x2, w))
                    y2 = max(0, min(y2, h))

                    if x2 <= x1 or y2 <= y1:
                        continue

                    boxes.append([x1, y1, x2, y2])
                    labels.append(int(cls) + 1)  # +1 vì label 0 là background

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        if boxes.numel() == 0:
            boxes = torch.zeros((0, 4), dtype=torch.float32)
            labels = torch.zeros((0,), dtype=torch.int64)

        area = (boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1])
        iscrowd = torch.zeros((boxes.shape[0],), dtype=torch.int64)

        target = {
            "boxes": boxes,
            "labels": labels,
            "image_id": torch.tensor([idx]),
            "area": area,
            "iscrowd": iscrowd,
        }

        img = F.to_tensor(img)
        return img, target

## 4. DataLoader

In [8]:
def collate_fn(batch):
    return tuple(zip(*batch))


train_dataset = YoloFormatDetectionDataset(train_source)
val_dataset = YoloFormatDetectionDataset(val_source)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH,
    shuffle=True,
    num_workers=2,
    collate_fn=collate_fn,
    pin_memory=torch.cuda.is_available(),
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH,
    shuffle=False,
    num_workers=2,
    collate_fn=collate_fn,
    pin_memory=torch.cuda.is_available(),
)

print("Train images:", len(train_dataset))
print("Val images  :", len(val_dataset))

Train images: 2800
Val images  : 800

## 5. Tạo model Faster R-CNN

In [9]:
weights = FasterRCNN_ResNet50_FPN_Weights.DEFAULT

model = fasterrcnn_resnet50_fpn(
    weights=weights,
    min_size=IMGSZ,
    max_size=IMGSZ,
)

in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

model.to(DEVICE)

params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(
    params,
    lr=0.005,
    momentum=0.9,
    weight_decay=0.0005,
)

lr_scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer,
    step_size=10,
    gamma=0.1,
)

scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

print(model.__class__.__name__)

Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth

100%|██████████| 160M/160M [00:02<00:00, 71.8MB/s]

FasterRCNN

/tmp/ipykernel_10521/658116426.py:28: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

## 6. Hàm eval COCO mAP trên tập validation

In [10]:
def evaluate_model(model, data_loader, device):
    metric = MeanAveragePrecision(
        box_format="xyxy",
        iou_type="bbox",
        class_metrics=True,
    )

    model.eval()

    with torch.no_grad():
        for images, targets in tqdm(data_loader, desc="Evaluating", leave=False):
            images = [img.to(device) for img in images]
            outputs = model(images)

            preds = []
            gts = []

            for output, target in zip(outputs, targets):
                preds.append({
                    "boxes": output["boxes"].detach().cpu(),
                    "scores": output["scores"].detach().cpu(),
                    "labels": output["labels"].detach().cpu(),
                })
                gts.append({
                    "boxes": target["boxes"].detach().cpu(),
                    "labels": target["labels"].detach().cpu(),
                })

            metric.update(preds, gts)

    return metric.compute()


def tensor_to_python(x):
    if torch.is_tensor(x):
        if x.numel() == 1:
            return float(x.detach().cpu().item())
        return x.detach().cpu().tolist()
    return x


def save_eval_results(results, save_dir, filename_prefix="metrics_fasterrcnn"):
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    summary = {
        "model": "Faster R-CNN ResNet50-FPN",
        "epochs": EPOCHS,
        "batch": BATCH,
        "imgsz": IMGSZ,
        "map_50_95": tensor_to_python(results["map"]),
        "map_50": tensor_to_python(results["map_50"]),
        "map_75": tensor_to_python(results["map_75"]),
        "map_small": tensor_to_python(results["map_small"]),
        "map_medium": tensor_to_python(results["map_medium"]),
        "map_large": tensor_to_python(results["map_large"]),
        "mar_1": tensor_to_python(results["mar_1"]),
        "mar_10": tensor_to_python(results["mar_10"]),
        "mar_100": tensor_to_python(results["mar_100"]),
    }

    summary_df = pd.DataFrame([summary])
    summary_csv = save_dir / f"{filename_prefix}_summary.csv"
    summary_json = save_dir / f"{filename_prefix}_summary.json"
    summary_df.to_csv(summary_csv, index=False)
    with open(summary_json, "w") as f:
        json.dump(summary, f, indent=2)

    per_class_rows = []
    classes = results.get("classes", torch.tensor([])).detach().cpu().tolist()
    map_per_class = results.get("map_per_class", torch.tensor([])).detach().cpu().tolist()
    mar_per_class = results.get("mar_100_per_class", torch.tensor([])).detach().cpu().tolist()

    for cls_id, ap, ar in zip(classes, map_per_class, mar_per_class):
        cls_id = int(cls_id)
        name_idx = cls_id - 1  # label 0 là background
        class_name = class_names[name_idx] if 0 <= name_idx < len(class_names) else f"class_{cls_id}"
        per_class_rows.append({
            "model": "Faster R-CNN ResNet50-FPN",
            "class_id_frcnn": cls_id,
            "class_id_yolo_equivalent": cls_id - 1,
            "class_name": class_name,
            "ap_50_95": float(ap),
            "ar_100": float(ar),
        })

    per_class_df = pd.DataFrame(per_class_rows)
    per_class_csv = save_dir / f"{filename_prefix}_per_class.csv"
    per_class_df.to_csv(per_class_csv, index=False)

    return summary_df, per_class_df, summary_csv, summary_json, per_class_csv

## 7. Train 30 epochs + eval trên val sau mỗi epoch

`best.pt` được lưu theo metric `mAP@0.50:0.95` cao nhất trên tập validation.

In [11]:
best_map = -1.0
history = []
last_ckpt_path = SAVE_DIR / "last.pt"
best_ckpt_path = SAVE_DIR / "best.pt"

for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0.0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch + 1}/{EPOCHS}")

    for images, targets in pbar:
        images = [img.to(DEVICE) for img in images]
        targets = [{k: v.to(DEVICE) for k, v in t.items()} for t in targets]

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=USE_AMP):
            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())

        scaler.scale(losses).backward()
        scaler.step(optimizer)
        scaler.update()

        loss_value = float(losses.detach().cpu().item())
        epoch_loss += loss_value
        pbar.set_postfix({
            "loss": f"{loss_value:.4f}",
            "lr": optimizer.param_groups[0]["lr"],
        })

    lr_scheduler.step()

    avg_train_loss = epoch_loss / max(1, len(train_loader))

    val_results = evaluate_model(model, val_loader, DEVICE)
    val_map = float(val_results["map"].detach().cpu().item())
    val_map50 = float(val_results["map_50"].detach().cpu().item())

    row = {
        "epoch": epoch + 1,
        "train_loss": avg_train_loss,
        "val_map_50_95": val_map,
        "val_map_50": val_map50,
        "lr": optimizer.param_groups[0]["lr"],
    }
    history.append(row)
    pd.DataFrame(history).to_csv(SAVE_DIR / "training_history.csv", index=False)

    checkpoint = {
        "epoch": epoch + 1,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "lr_scheduler_state_dict": lr_scheduler.state_dict(),
        "class_names": class_names,
        "num_classes": num_classes,
        "imgsz": IMGSZ,
        "batch": BATCH,
        "epochs": EPOCHS,
        "val_map_50_95": val_map,
        "val_map_50": val_map50,
    }

    torch.save(checkpoint, last_ckpt_path)

    if val_map > best_map:
        best_map = val_map
        torch.save(checkpoint, best_ckpt_path)
        print(f"Saved best.pt | epoch={epoch + 1} | mAP50-95={best_map:.4f}")

    print(
        f"Epoch [{epoch + 1}/{EPOCHS}] "
        f"train_loss={avg_train_loss:.4f} "
        f"val_mAP50-95={val_map:.4f} "
        f"val_mAP50={val_map50:.4f}"
    )

print("Training completed.")
print("Best checkpoint:", best_ckpt_path)
print("Last checkpoint:", last_ckpt_path)

Epoch 1/30:   0%|          | 0/175 [00:00<?, ?it/s]

/tmp/ipykernel_10521/1606334102.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=USE_AMP):

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=1 | mAP50-95=0.0160
Epoch [1/30] train_loss=0.7003 val_mAP50-95=0.0160 val_mAP50=0.0513

Epoch 2/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=2 | mAP50-95=0.0304
Epoch [2/30] train_loss=0.5932 val_mAP50-95=0.0304 val_mAP50=0.0903

Epoch 3/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
     assert self._parent_pid == os.getpid(), 'can only test a child process'
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Saved best.pt | epoch=3 | mAP50-95=0.0484
Epoch [3/30] train_loss=0.5452 val_mAP50-95=0.0484 val_mAP50=0.1421

Epoch 4/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=4 | mAP50-95=0.0587
Epoch [4/30] train_loss=0.5141 val_mAP50-95=0.0587 val_mAP50=0.1669

Epoch 5/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=5 | mAP50-95=0.0749
Epoch [5/30] train_loss=0.4723 val_mAP50-95=0.0749 val_mAP50=0.2013

Epoch 6/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=6 | mAP50-95=0.0818
Epoch [6/30] train_loss=0.4389 val_mAP50-95=0.0818 val_mAP50=0.2188

Epoch 7/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=7 | mAP50-95=0.0962
Epoch [7/30] train_loss=0.4129 val_mAP50-95=0.0962 val_mAP50=0.2501

Epoch 8/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=8 | mAP50-95=0.1100
Epoch [8/30] train_loss=0.3837 val_mAP50-95=0.1100 val_mAP50=0.2724

Epoch 9/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [9/30] train_loss=0.3585 val_mAP50-95=0.1088 val_mAP50=0.2715

Epoch 10/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=10 | mAP50-95=0.1176
Epoch [10/30] train_loss=0.3355 val_mAP50-95=0.1176 val_mAP50=0.2891

Epoch 11/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=11 | mAP50-95=0.1243
Epoch [11/30] train_loss=0.2834 val_mAP50-95=0.1243 val_mAP50=0.2966

Epoch 12/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>^
^Traceback (most recent call last):
^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
^^    self._shutdown_workers()^^
^^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
^^^    ^if w.is_alive():^
^^ ^ ^^^^  ^^^^^^ ^^^
 ^AssertionError^: ^can only test a child process^
^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
       Exception ignored in:   <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
^^Traceback (most recent call last):
^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
^    ^self._shutdown_workers()
^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
^^    ^if w.is_alive():^
^ ^^  ^^  ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive

    AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process':
can only test a child process
          ^^^^^^^^^^^^^Exception ignored in: ^^<function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>^
Traceback (most recent call last):
^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
^^    self._shutdown_workers()^
^  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
^    ^if w.is_alive():^^
^  ^ ^^  ^  ^
AssertionError: can only test a child process^^
^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
     assert self._parent_pid == os.getpid(), 'can only test a child process'
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Saved best.pt | epoch=12 | mAP50-95=0.1262
Epoch [12/30] train_loss=0.2700 val_mAP50-95=0.1262 val_mAP50=0.3016

Epoch 13/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Saved best.pt | epoch=13 | mAP50-95=0.1277
Epoch [13/30] train_loss=0.2628 val_mAP50-95=0.1277 val_mAP50=0.3057

Epoch 14/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [14/30] train_loss=0.2571 val_mAP50-95=0.1245 val_mAP50=0.2994

Epoch 15/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [15/30] train_loss=0.2517 val_mAP50-95=0.1212 val_mAP50=0.3001

Epoch 16/30:   0%|          | 0/175 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [16/30] train_loss=0.2453 val_mAP50-95=0.1263 val_mAP50=0.3085

Epoch 17/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [17/30] train_loss=0.2406 val_mAP50-95=0.1252 val_mAP50=0.3040

Epoch 18/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [18/30] train_loss=0.2361 val_mAP50-95=0.1219 val_mAP50=0.3032

Epoch 19/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [19/30] train_loss=0.2298 val_mAP50-95=0.1232 val_mAP50=0.2984

Epoch 20/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [20/30] train_loss=0.2253 val_mAP50-95=0.1225 val_mAP50=0.2981

Epoch 21/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [21/30] train_loss=0.2177 val_mAP50-95=0.1212 val_mAP50=0.2993

Epoch 22/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [22/30] train_loss=0.2170 val_mAP50-95=0.1221 val_mAP50=0.2961

Epoch 23/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [23/30] train_loss=0.2156 val_mAP50-95=0.1206 val_mAP50=0.2985

Epoch 24/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [24/30] train_loss=0.2160 val_mAP50-95=0.1220 val_mAP50=0.2976

Epoch 25/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [25/30] train_loss=0.2152 val_mAP50-95=0.1213 val_mAP50=0.2978

Epoch 26/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [26/30] train_loss=0.2145 val_mAP50-95=0.1209 val_mAP50=0.2988

Epoch 27/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [27/30] train_loss=0.2142 val_mAP50-95=0.1197 val_mAP50=0.3003

Epoch 28/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7aaa3c211a80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1707, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1690, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [28/30] train_loss=0.2132 val_mAP50-95=0.1204 val_mAP50=0.2967

Epoch 29/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [29/30] train_loss=0.2135 val_mAP50-95=0.1202 val_mAP50=0.2976

Epoch 30/30:   0%|          | 0/175 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch [30/30] train_loss=0.2132 val_mAP50-95=0.1214 val_mAP50=0.2977
Training completed.
Best checkpoint: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/best.pt
Last checkpoint: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/last.pt

## 8. Load `best.pt` và eval cuối cùng trên cùng tập validation

In [12]:
checkpoint = torch.load(best_ckpt_path, map_location=DEVICE)
model.load_state_dict(checkpoint["model_state_dict"])
model.to(DEVICE)
model.eval()

final_results = evaluate_model(model, val_loader, DEVICE)

summary_df, per_class_df, summary_csv, summary_json, per_class_csv = save_eval_results(
    final_results,
    SAVE_DIR,
    filename_prefix="metrics_fasterrcnn",
)

print("===== Faster R-CNN Overall Metrics =====")
display(summary_df)

print("===== Faster R-CNN Per-class Metrics =====")
display(per_class_df)

print("Saved summary CSV:", summary_csv)
print("Saved summary JSON:", summary_json)
print("Saved per-class CSV:", per_class_csv)

Evaluating:   0%|          | 0/50 [00:00<?, ?it/s]

===== Faster R-CNN Overall Metrics =====

,model,epochs,batch,imgsz,map_50_95,map_50,map_75,map_small,map_medium,map_large,mar_1,mar_10,mar_100
0,Faster R-CNN ResNet50-FPN,30,16,640,0.127722,0.305678,0.084241,0.000179,0.006529,0.144076,0.186513,0.32329,0.32757

===== Faster R-CNN Per-class Metrics =====

,model,class_id_frcnn,class_id_yolo_equivalent,class_name,ap_50_95,ar_100
0,Faster R-CNN ResNet50-FPN,1,0,crack,0.120418,0.379141
1,Faster R-CNN ResNet50-FPN,2,1,dent,0.119089,0.331911
2,Faster R-CNN ResNet50-FPN,3,2,glass shatter,0.061094,0.228346
3,Faster R-CNN ResNet50-FPN,4,3,lamp broken,0.104036,0.282836
4,Faster R-CNN ResNet50-FPN,5,4,scratch,0.160467,0.367473
5,Faster R-CNN ResNet50-FPN,6,5,tire flat,0.201228,0.375714

Saved summary CSV: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/metrics_fasterrcnn_summary.csv
Saved summary JSON: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/metrics_fasterrcnn_summary.json
Saved per-class CSV: /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/metrics_fasterrcnn_per_class.csv

## 9. In nhanh đường dẫn output

In [13]:
print("Output dir       :", SAVE_DIR)
print("Best checkpoint  :", best_ckpt_path)
print("Last checkpoint  :", last_ckpt_path)
print("Training history :", SAVE_DIR / "training_history.csv")
print("Summary CSV      :", summary_csv)
print("Per-class CSV    :", per_class_csv)

Output dir       : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640
Best checkpoint  : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/best.pt
Last checkpoint  : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/last.pt
Training history : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/training_history.csv
Summary CSV      : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/metrics_fasterrcnn_summary.csv
Per-class CSV    : /content/drive/MyDrive/coco_damage_car_yolov8/fasterrcnn_car_30e_640/metrics_fasterrcnn_per_class.csv